CREATE TABLE IF NOT EXISTS component_excel_import (
    mpn TEXT,
    manufacturer TEXT,
    manufacturer_part_number TEXT,
    supplier_part_number TEXT,
    rohs TEXT,
    description TEXT,
    category TEXT,
    lifecycle_status TEXT,
    stock TEXT,
    datasheet_url TEXT,
    product_url TEXT,
    msd_level TEXT,
    reflow_soldering_temperature TEXT,
    thermal_cycle TEXT,
    wave_soldering_temperature TEXT,
    lsl_details TEXT,
    package_details TEXT,
    price_details TEXT,
    operating_temperature TEXT,
    component_thickness TEXT,
    reach TEXT,
    reflow_soldering_time TEXT,
    wave_soldering_time TEXT,
    body_mark TEXT
);
